<a href="https://www.kaggle.com/code/barri12/visualization-with-pandas-on-avocados-sales-data?scriptVersionId=109290221" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
"""
Avocados are increasingly popular and delicious in guacamole and on toast. 
The Hass Avocado Board keeps track of avocado supply and demand across the USA, including the sales of three different 
sizes of avocado. In this exercise, we'll use a bar plot to figure out which size is the most popular.
"""

In [ ]:
# For each avocado size group, calculate the total number sold
# Create a bar plot of the number of avocados sold by size

In [2]:
avocados = pd.read_pickle("../input/datamanipulationwithpandas/avoplotto.pkl")
avocados.head()

         date          type  year  avg_price   size     nb_sold
0  2015-12-27  conventional  2015       0.95  small  9626901.09
1  2015-12-20  conventional  2015       0.98  small  8710021.76
2  2015-12-13  conventional  2015       0.93  small  9855053.66
3  2015-12-06  conventional  2015       0.89  small  9405464.36
4  2015-11-29  conventional  2015       0.99  small  8094803.56

In [6]:
# to print out the first entries in size
gg = avocados.groupby("size")
gg.first()

# we find out there are three sizes namely - extra_large, large, and small.

                   date          type  year  avg_price      nb_sold
size
extra_large  2015-12-27  conventional  2015       0.95   1184340.09
large        2015-12-27  conventional  2015       0.95  10197890.05
small        2015-12-27  conventional  2015       0.95   9626901.09

In [ ]:
# Get the total number of avocados sold of each size
nb_sold_by_size = avocados.groupby("size")["nb_sold"].sum()

# Create a bar plot of the number of avocados sold by size
nb_sold_by_size.plot(kind = "bar")

# Show the plot
plt.show()

In [ ]:
# Visualize the changes in sales over three years
# Get the total number of avocados sold on each date
nb_sold_by_date = avocados.groupby("date")["nb_sold"].sum()

# Create a line plot of the number of avocados sold by date
nb_sold_by_date.plot(kind="line")

# Show the plot
plt.show()

In [ ]:
# Scatter plots are ideal for visualizing relationships between numerical variables. We'll compare the number of avocados sold to average price and see if they're at all related. If they're related, you may be able to use one number to predict the other.

# Scatter plot of avg_price vs. nb_sold with title
avocados.plot(x = "nb_sold", y = "avg_price", kind = "scatter", title = "Number of avocados sold vs. average price")

# Show the plot
plt.show()

In [ ]:
# price of conventional vs. organic avocados
# We'll create multiple histograms to compare the prices of conventional and organic avocados.

# Histogram of conventional avg_price 
avocados[avocados["type"] == "conventional"]["avg_price"].hist()

# Histogram of organic avg_price
avocados[avocados["type"] == "organic"]["avg_price"].hist()

# Add a legend
plt.legend(["conventional", "organic"])

# Show the plot
plt.show()

In [ ]:
# Modify your code to adjust the transparency of both histograms 
# Modify histogram transparency to 0.5 
avocados[avocados["type"] == "conventional"]["avg_price"].hist(alpha = 0.5)

# Modify histogram transparency to 0.5
avocados[avocados["type"] == "organic"]["avg_price"].hist(alpha = 0.5)

# Add a legend
plt.legend(["conventional", "organic"])

plt.show()

In [ ]:
# Modify bins to 20
avocados[avocados["type"] == "conventional"]["avg_price"].hist(alpha=0.5, bins = 20)

# Modify bins to 20
avocados[avocados["type"] == "organic"]["avg_price"].hist(alpha=0.5, bins = 20)

# Add a legend
plt.legend(["conventional", "organic"])

# Show the plot
plt.show()

In [ ]:
# DEALING WITH MISSING VALUES


# Check individual values for missing values
print(avocados.isna())

# Check each column for missing values
print(avocados.isna().any())

# Bar plot of missing values by variable
avocados.isna().sum().plot(kind="bar")

# Show plot
plt.show()

In [ ]:
# Remove rows with missing values
avocados_complete = avocados.dropna()

# Check if any columns contain missing values
print(avocados_complete.isna().any())

In [ ]:
# Replacing missing values
# List the columns with missing values
cols_with_missing = ["small_sold", "large_sold", "xl_sold"]

# Create histograms showing the distributions cols_with_missing
avocados_2016[(cols_with_missing)].hist()

# Show the plot
plt.show()

In [ ]:
# From previous step
cols_with_missing = ["small_sold", "large_sold", "xl_sold"]
avocados[cols_with_missing].hist()
plt.show()

# Fill in missing values with 0
avocados_filled = avocados.fillna(0)

# Create histograms of the filled columns
avocados_filled[cols_with_missing].hist()

# Show the plot
plt.show()